spring.datasource.url=jdbc:sqlserver://SF-KTABORDA:1433;databaseName=SMRED;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=TdeA.2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.application.name=NetworkMonitor
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO@gmail.com
spring.mail.password=TU_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
monitor.ping.interval=30000
monitor.portscan.interval=300000
monitor.bandwidth.interval=10000
monitor.alert.latency-threshold=500
monitor.alert.packet-loss-threshold=20
monitor.alert.email-enabled=false
monitor.alert.email-to=admin@empresa.com
logging.level.com.networkmonitor=INFO
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
